src:
 host: "0.0.0.0"
 port: 8000

payload_handling:
  # Global rules that apply to all traffic
  global:
    delay:
      - action: ""
        delay_ms: 0
    block:
      - action: ""
    insert_data: # New section for global insert_data rules
      - action: "global_insert_test_bytes"
        data: "Hello from global rule"
        data_type: "bytes" # "bytes" or "hex"
        position: "before" # "before" or "after"
        delay_sec: 0 # Seconds to wait after proxy start
      - action: "global_insert_test_hex"
        data: "aabbccddeeff"
        data_type: "hex"
        position: "after"
        delay_sec: 5

  # Direction-specific rules
  directions:
    # Rules for traffic from Alice to Bob
    alice_to_bob:
      source_ip: "192.168.1.100"  # Alice's IP
      target_ip: "192.168.1.101"  # Bob's IP
      delay:
        - action: ""
          delay_ms: 0
      block:
        - action: ""
      insert_data: # New section for direction-specific insert_data rules
        - action: "alice_insert_test_bytes"
          data: "Data for Bob"
          data_type: "bytes"
          position: "before"
          delay_sec: 0

    # Rules for traffic from Bob to Alice
    bob_to_alice:
      source_ip: "192.168.1.101"  # Bob's IP
      target_ip: "192.168.1.100"  # Alice's IP
      delay:
        - action: ""
          delay_ms: 0
      block:
        - action: ""
      insert_data:
        - action: "bob_insert_test_hex"
          data: "0102030405"
          data_type: "hex"
          position: "after"
          delay_sec: 10
