src:
 host: "0.0.0.0"
 port: 8000

payload_handling:
  global:
    delay: []
    block: []
    insert: []

  directions:
    alice_to_bob:
      source_ip: "10.10.20.11"
      target_ip: "10.10.20.13"
      delay: []
      block: []
      insert: []

    bob_to_alice:
      source_ip: "10.10.20.13"
      target_ip: "10.10.20.11"
      delay: []
      block: []
      insert: []

attack_mode:
  alice_to_bob:
    enabled: true
    malicious_pickle_payload: "80049524000000000000008c207072696e7428274d49544d2041747461636b205375636365737366756c212729942e"
    log: true
  bob_to_alice:
    enabled: true
    malicious_pickle_payload: ""
    log: true