src:
 host: "0.0.0.0"
 port: 8000

payload_handling:
  global:
    delay:
      - action: ""
        delay_ms: 0
    block:
      - action: ""
    insert:
      - action: ""
        position: "before"
        data: "deadbeef"
        repeat: 1
    replay:
      - action: ""
        count: 3
        block_original: true
        position: "after"

  directions:
    alice_to_bob:
      source_ip: "10.10.20.11"
      target_ip: "10.10.20.13"
      insert:
        - action: ""
          position: "after"
          data: "deadbeef"
          repeat: false
      replay:
        - action: ""
          count: 2
          block_original: false
          delay_ms: 50
          position: "before"

    bob_to_alice:
      source_ip: "10.10.20.13"
      target_ip: "10.10.20.11"
      insert:
        - action: ""
          position: "before"
          data: "deadbeef"
          repeat: true
