src:
 host: "0.0.0.0"
 port: 8000

payload_handling:
  global:
    delay:
      - action: ""
        delay_ms: 0
    block:
      - action: ""
    insert:
      - action: ""
        position: "before"
        data: "deadbeef"
        repeat: 1

  directions:
    alice_to_bob:
      source_ip: "10.10.20.11"
      target_ip: "10.10.20.13"
      delay:
        - action: ""
          delay_ms: 0
      block:
        - action: ""
      insert:
        - action: "u"
          position: "after"
          data: "deadbeef"
          repeat: 3
        - action: ""
          position: "before"
          data: "deadbeef"
          delay_ms: 100
          repeat: true

    bob_to_alice:
      source_ip: "10.10.20.13"
      target_ip: "10.10.20.11"
      delay:
        - action: ""
          delay_ms: 0
      block:
        - action: ""
      insert:
        - action: ""
          position: "before"
          data: "deadbeef"
          repeat: false

attack_mode:
  alice_to_bob:
    enabled: true
    malicious_pickle_payload: "800495abcdef..."
    log: true
  bob_to_alice:
    enabled: false
    malicious_pickle_payload: ""
    log: true